name = "dogeub"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./dist"

[[durable_objects.bindings]]
name = "BARE_SERVER"
class_name = "BareServer"

[[migrations]]
tag = "v1"
new_classes = ["BareServer"]
